#!/usr/bin/env bash

# Display listening ports
echo "Listening ports:"
netstat -ltnp

# Display the PID and name of the program to which each socket belongs
echo "PID and program name:"
netstat -tulpn
