#!/usr/bin/env bash
# Pings an IP address received as an argument 5 times.

# IP variable
IP="${1}"

# fn is filename variable
fn=$(basename "${BASH_SOURCE[0]}")

if [ -z "${IP}" ]; then
    echo "Usage: ${fn} {IP_ADDRESS}"
else
    ping -c 5 "${IP}"
fi
