#!/usr/bin/env bash
# Pings an IP address received as an argument 5 times.
#IP variable
IP = "${1}"
# fn is filename variable
fn =$(basename "${bash_source}")
if !["IP"];then
	echo "usage: ${fn} {IP_ADDRESS}"
else
	ping -c 5 "${IP}"
fi
