#!/usr/bin/env bash
#a Bash script that displays Best School 10 times with
#while and for 

i=1
while [ $i -le 11 ]
do
	if [ $i -eq 10 ];then
		echo "Hi"
	else
		echo "Best School"
	fi
	i=$((i+1))
done
