#!/usr/bin/env bash
#Write a Bash script that displays the time for 12 hours and 59 minutes:
#display hours from 0 to 12
#display minutes from 1 to 59

i=0
j=1
while [ $i -lt 12 ]
do
	while [ $j -le 59 ]
	do
		if [[ $j -eq 1 && $i -eq 0 ]];then
			echo "Hour:"$i
			echo "$j"
		elif [ $j -eq 59 ];then
			echo "$j"
			i=$((i+1))
			echo "Hour:"$i
		else
			echo "$j"
		fi
		j=$((j+1))
	done
	j=1
done

